In [1]:
#!pip install tsp
#Dominik Jagoda
#Algorytmy Ewolucyjne Inżynieria Danych III rok

In [2]:
import tsp
import numpy as np
#import matplotlib.pyplot as plt
import time

In [3]:
#DANE
#https://dateandtime.info/pl/citycoordinates.php?id=3094802
#https://www.wspolrzedne-gps.pl

In [4]:
all_cit=np.array([
             [50.8703300,20.6275200],#Kielce
             [50.6826500,21.7489800],#Sandomierz
    [50.8520727,19.9667772],#Włoszczowa
    [50.6394435,20.3046116],#Jędrzejów
    [50.5201929,20.5256241],#Pinczów
    [50.46759,20.71919],#Busko-Zdrój
    [50.267489,20.4853308],#Kazimierza Wileka
    [50.5612276,21.1677849],#Staszów
    [50.8017661,21.4238281],#Opatów
    [50.9398768,21.38743],#Ostrowiec Świętokrzyski
    [51.0518865,21.0761377],#Starachowice
    [51.1138821,20.857883],#Skarżysko Kamienna
    [51.1910223,20.4071836],#Końskie
    [50.0614300,19.9365800],#Kraków
    [50.3566016,20.0276912],#Miechów
    [50.2788158,19.5596307],#Olkusz
    [50.1411926,19.4028502],#Chrzanów
    [50.0382443,19.2214053],#Oświęcim
    [49.8834484,19.4925345],#Wadowica
    [49.834608,19.9384283],#Myślenice
    [49.74079,19.5905975],#Sucha Beskidzka
    [49.4818229,20.030541],#Nowy targ
    [49.2969446,19.950659],#Zakopane
    [49.7061713,20.4217266],#Limanowa
    [49.6249173,20.691346],#Nowy Sacz
#    [49.65829,21.1593832],#Gorlice
#    [50.0123784,20.9880739],#Tarnow
#    [49.9678396,20.6068496],#Brzesko
#    [49.9693563,20.430541],#Bochnia
#    [50.1743495,20.9850707],#Dąbrowa tarnowska
#    [49.9823773,20.0602114],#Wieliczka
#    [50.5653105,22.0644075],#Stalowa Wola
#    [50.5715277,21.6704871],#Tarnobrzeg
#    [50.5198985,22.139886],#Nisko
#    [50.2892506,21.4243685],#Mielec
#    [50.2433277,21.7754563],#Kolbuszowa
#    [50.2621687,22.418892],#Leżajsk
#    [50.1574473,23.1225859],#Lubaczów
#    [50.0104958,22.678605],#Jarosław
#    [50.0601735,22.4923769],#Przeworsk
#    [50.0690725,22.2320924],#Łańcut
#    [50.0528608,21.6116324],#Ropczyce
#    [50.0514601,21.4104804],#Dębica
#    [49.7470465,21.4743139],#Jasło
#    [49.870208,21.7856291],#Strzyżów
#    [49.6938045,21.7651458],#Krosno
    [49.6950395,22.0196537],#Brzozów
    [49.5609053,22.207028],#Sanok
    [49.7821562,22.7692634],#Przemyśl
    [49.4689014,22.3303816],#Lesko
    [49.4301874,22.5877003],#Ustrzyki Dolne
    [50.0413200,21.9990100]#Rzeszów
            
])

n=len(all_cit)

In [5]:
n

31

In [6]:
import math as m

In [7]:

def dist(i,j):
    R=6400
    if i == j:
        return 0
    else:
        return R*np.arccos((m.sin(all_cit[i,1]/180)*m.sin(all_cit[j,1]/180) +
               m.cos(all_cit[i,1]/180)*m.cos(all_cit[j,1]/180)*m.cos((all_cit[i,0]/180)-(all_cit[j,0]/180))))

In [8]:
dist(1,2)

63.64908168420394

In [9]:
all_cit[0]


array([50.87033, 20.62752])

In [10]:
#def all_dist(i,j): # funkcja odległości między wszystkimi miastami
    #return np.sqrt((all_cit[i,0]-all_cit[j,0])**2 + (all_cit[i,1]-all_cit[j,1])**2)

In [11]:
dt=[[dist(i,j) for i in range(n)] for j in range(n)]
np.round(np.array(dt),2)

array([[  0.  ,  40.42,  23.5 ,  14.08,  12.89,  14.59,  21.89,  22.09,
         28.42,  27.13,  17.19,  11.88,  13.77,  37.69,  28.  ,  43.34,
         50.6 ,  58.  ,  53.33,  44.04,  54.33,  53.45,  60.57,  41.77,
         44.05,  64.59,  72.74,  85.29,  78.19,  86.27,  56.87],
       [ 40.42,   0.  ,  63.65,  51.38,  43.87,  37.39,  47.26,  21.1 ,
         12.3 ,  15.74,  27.24,  35.15,  50.97,  68.07,  62.28,  79.14,
         85.58,  92.71,  85.05,  71.  ,  83.64,  74.38,  80.52,  58.45,
         53.  ,  36.16,  42.81,  48.22,  47.56,  53.31,  24.32],
       [ 23.5 ,  63.65,   0.  ,  14.17,  23.07,  30.  ,  27.69,  43.92,
         51.84,  50.61,  40.07,  33.01,  19.71,  27.96,  17.64,  24.9 ,
         32.14,  39.11,  38.16,  35.97,  41.49,  48.47,  54.96,  43.6 ,
         50.43,  83.65,  91.78, 106.56,  97.2 , 105.85,  77.72],
       [ 14.08,  51.38,  14.17,   0.  ,   8.92,  15.94,  14.63,  30.81,
         40.21,  39.94,  31.06,  25.84,  19.82,  24.26,  14.03,  29.39,
         36.5

In [12]:
# konwersja tablicy odległości do słownika (potrzebne dalej dla wołania f. bibliotecznej)
dis = {(i, j): dt[i][j] for i in range(n) for j in range(n)}

In [13]:
dis

{(0, 0): 0,
 (0, 1): 40.421058976689906,
 (0, 2): 23.50193056631973,
 (0, 3): 14.083420433339292,
 (0, 4): 12.887781523036873,
 (0, 5): 14.593929845232529,
 (0, 6): 21.8866274210338,
 (0, 7): 22.09451914982001,
 (0, 8): 28.416513827479655,
 (0, 9): 27.130412100144124,
 (0, 10): 17.191403797175443,
 (0, 11): 11.87792359362484,
 (0, 12): 13.773417932751839,
 (0, 13): 37.686274003712825,
 (0, 14): 28.004591173113408,
 (0, 15): 43.34182113380751,
 (0, 16): 50.5953052003859,
 (0, 17): 58.00104925123796,
 (0, 18): 53.33425609959617,
 (0, 19): 44.0372850770914,
 (0, 20): 54.33381867761673,
 (0, 21): 53.44990954403698,
 (0, 22): 60.573562157529324,
 (0, 23): 41.7694018480022,
 (0, 24): 44.04849282146377,
 (0, 25): 64.5902887509444,
 (0, 26): 72.739292027866,
 (0, 27): 85.28923833976403,
 (0, 28): 78.18901516991782,
 (0, 29): 86.26566790505987,
 (0, 30): 56.87386920571542,
 (1, 0): 40.421058976689906,
 (1, 1): 0,
 (1, 2): 63.64908168420394,
 (1, 3): 51.377980872363516,
 (1, 4): 43.8737343960819

In [14]:
time0 = time.time()    # czas start
t_tsp = tsp.tsp(range(n),dis) # znajdź DOKŁADNE rozwiązanie
time1 = time.time()    # czas stop

print(t_tsp)
print("czas wykonania:",round(time1 - time0,1),"s")

(422.17721010277114, [0, 12, 2, 3, 4, 5, 6, 14, 13, 15, 16, 17, 18, 20, 19, 22, 21, 23, 24, 25, 26, 28, 29, 27, 30, 1, 7, 8, 9, 10, 11])
czas wykonania: 16.8 s


In [15]:
p_tsp=np.array(t_tsp[1]) # najkrótsza trasa
t_tsp[0] # długość najkrótszej trasy

422.17721010277114

In [16]:
#Komórka ta powoduje zamknięcie trasy 
t=t_tsp[1]
index=0
route=np.insert(np.append(t,0),0,0)
route=np.delete(route,index)
tour=np.array([all_cit[i] for i in route])
tour


array([[50.87033  , 20.62752  ],
       [51.1910223, 20.4071836],
       [50.8520727, 19.9667772],
       [50.6394435, 20.3046116],
       [50.5201929, 20.5256241],
       [50.46759  , 20.71919  ],
       [50.267489 , 20.4853308],
       [50.3566016, 20.0276912],
       [50.06143  , 19.93658  ],
       [50.2788158, 19.5596307],
       [50.1411926, 19.4028502],
       [50.0382443, 19.2214053],
       [49.8834484, 19.4925345],
       [49.74079  , 19.5905975],
       [49.834608 , 19.9384283],
       [49.2969446, 19.950659 ],
       [49.4818229, 20.030541 ],
       [49.7061713, 20.4217266],
       [49.6249173, 20.691346 ],
       [49.6950395, 22.0196537],
       [49.5609053, 22.207028 ],
       [49.4689014, 22.3303816],
       [49.4301874, 22.5877003],
       [49.7821562, 22.7692634],
       [50.04132  , 21.99901  ],
       [50.68265  , 21.74898  ],
       [50.5612276, 21.1677849],
       [50.8017661, 21.4238281],
       [50.9398768, 21.38743  ],
       [51.0518865, 21.0761377],
       [51

In [17]:

lenpa=np.round(t_tsp[0],3) # długość najkrótszej trasy
lenpa

422.177

In [18]:
#!pip install folium

In [19]:

import folium

In [20]:
my_map = folium.Map([50.0614300,19.9365800])
for i in tour:
    folium.Marker(i).add_to(my_map)
my_map

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
my_map = folium.Map([50.0614300,19.9365800])
for i in tour:
    folium.Marker(i).add_to(my_map)
    
folium.PolyLine(tour, color="red", weight=2.5, opacity=1).add_to(my_map)
my_map

In [ ]:
my_map = folium.Map([50.0614300,19.9365800])
    
folium.PolyLine(tour, color="red", weight=2.5, opacity=1).add_to(my_map)
my_map